---
- name: Delete prevous k8s binaries
  file:
    state: absent
    path: /usr/local/bin/kubernetes
  when:
  - ansible_fqdn in groups['workers'] or ansible_fqdn in groups['storage']
  - ansible_fqdn not in groups['masters']
