---
- name: Restart Containerd
  systemd:
    state: restarted
    name: containerd

- name: Reload Containerd
  systemd:
    state: restarted
    daemon_reload: yes
    name: containerd

- name: Reload Docker
  systemd:
    state: restarted
    daemon_reload: yes
    name: docker

- name: Restart Docker
  systemd:
    state: restarted
    name: docker
