---
- hosts: all
  any_errors_fatal: true
  become: true
  roles:
    - connexion-to-hosts
    - populate_etc_hosts
- hosts: deploy
  become: true
  roles:
    - compliance-checks
    - install-kubectl
    - install-go
    - generate-certs
- hosts: etcd
  become: true
  roles:
    - setup-etcd
- hosts: masters
  become: true
  roles:
    - setup-master
    - configure-kubeconfig
- hosts: workers
  become: true
  roles:
  - install-runtimes
  - setup-worker
- hosts: deploy
  become: true
  roles:
    - install-kubectl
    - configure-kubeconfig
    - install-helm
    - post-scripts
    - show-info
