- name: Include label hosts
  include_tasks: generate-kubernetes-pki.yaml

- name: Generate Keycloak PKI
  include_tasks: oidc-keycloak.yaml
  when:
    - agorakube_features.keycloak_oidc.auto_bootstrap.bootstrap_keycloak | bool == True
    - agorakube_features.keycloak_oidc.enabled | bool == True
