- name: Create oidc dir
  file:
    path: "{{ pki_path }}/oidc"
    state: directory

- name: Generate oidc-ca.key private keys
  openssl_privatekey:
    path: "{{ pki_path }}/oidc/oidc-ca.key"
    force: false

- name: Generate an OpenSSL Certificate Signing Request for OIDC CA
  openssl_csr:
    path: "{{ pki_path }}/oidc/oidc-ca.csr"
    privatekey_path: "{{ pki_path }}/oidc/oidc-ca.key"
    common_name: "{{ agorakube_pki.infos.country }}"
    state_or_province_name: "{{ agorakube_features.keycloak_oidc.auto_bootstrap.host }}"
    locality_name: "{{ agorakube_pki.infos.locality }}"
    country_name: "{{ agorakube_pki.infos.country }}"
    basic_constraints: ['CA:TRUE']

- name: Generate an OpenSSL certificate signed with your own OIDC CA certificate
  openssl_certificate:
    path: "{{ pki_path }}/oidc/oidc-ca.crt"
    privatekey_path: "{{ pki_path }}/oidc/oidc-ca.key"
    csr_path: "{{ pki_path }}/oidc/oidc-ca.csr"
    provider: selfsigned
    selfsigned_not_after: "{{ agorakube_pki.infos.expirity }}"
    force: false

- name: Generate oidc-end.key private keys
  openssl_privatekey:
    path: "{{ pki_path }}/oidc/oidc-end.key"
    force: false

- name: Generate an OpenSSL Certificate Signing Request for OIDC-END CSR
  openssl_csr:
    path: "{{ pki_path }}/oidc/oidc-end.csr"
    privatekey_path: "{{ pki_path }}/oidc/oidc-end.key"
    common_name: "{{ agorakube_features.keycloak_oidc.auto_bootstrap.host }}"
    state_or_province_name: "{{ agorakube_pki.infos.state }}"
    locality_name: "{{ agorakube_pki.infos.locality }}"
    country_name: "{{ agorakube_pki.infos.country }}"
    basic_constraints: ['CA:TRUE']

- name: Generate an OpenSSL certificate signed OIDC END certificate
  openssl_certificate:
    path: "{{ pki_path }}/oidc/oidc-end.crt"
    csr_path: "{{ pki_path }}/oidc/oidc-end.csr"
    ownca_path: "{{ pki_path }}/oidc/oidc-ca.crt"
    ownca_privatekey_path: "{{ pki_path }}/oidc/oidc-ca.key"
    provider: ownca
    force: false
