---
- name: Add the [overlay] and [br_netfilter]  modules
  modprobe:
    name: "{{ item }}"
    state: present
  with_items:
    - overlay
    - br_netfilter

- name: Create activated kernel modules directory
  file:
    path: /etc/modules-load.d/
    state: directory

- name: Load kernel modules at boot
  copy:
    content: "{{ item }}"
    dest: /etc/modules-load.d/{{ item }}.conf
  with_items:
    - overlay
    - br_netfilter

- name: Setup required sysctl params, these persist across reboots
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: yes
    sysctl_file: /etc/sysctl.d/99-kubernetes-cri.conf
  with_items:
    - { name: 'net.bridge.bridge-nf-call-iptables', value: '1' }
    - { name: 'net.ipv4.ip_forward', value: '1' }
    - { name: 'net.bridge.bridge-nf-call-ip6tables', value: '1' }

- name: Install Containerd from binaries
  unarchive:
    src: https://github.com/containerd/containerd/releases/download/v{{ containerd_release }}/containerd-{{ containerd_release }}.linux-amd64.tar.gz
    remote_src: yes
    dest: /usr/bin/
    extra_opts: [--strip-components=1]
  notify:
    - Restart Containerd

- name: Make sure service file existe at /etc/systemd/system/docker.service
  template:
    src: containerd.service.j2
    dest: /etc/systemd/system/containerd.service
  notify:
    - Reload Containerd
  register: containerd_servise_status

- name: Install Runc v1.0-RC10
  get_url:
    url: https://github.com/opencontainers/runc/releases/download/v1.0.0-rc10/runc.amd64
    dest: /usr/bin/runc
    mode: 0774

- name: Start Runtime
  systemd:
    state: started
    name: containerd
    enabled: yes
  when: containerd_servise_status.changed

- name: Create /etc/containerd directory
  file:
    path: /etc/containerd
    state: directory

- name: Configure containerd
  copy:
    src: config.toml
    dest: /etc/containerd/config.toml
  notify:
    - Restart Containerd

- name: Start Runtime
  systemd:
    state: started
    name: containerd
    enabled: yes
