---
- name: Install Docker from binaries
  unarchive:
    src: https://download.docker.com/linux/static/stable/x86_64/docker-{{ docker_release }}.tgz
    remote_src: yes
    dest: /usr/bin
    extra_opts: [--strip-components=1]
    owner: root
    group: root
  notify:
    - Restart Docker

- name: Create Docker.socket file
  copy:
    src: docker.socket
    dest: /etc/systemd/system/docker.socket
    owner: root
    group: root
  notify:
    - Reload Docker
  register: docker_socket_status


- name: Ensure group "docker" exists
  group:
    name: docker
    state: present

- name: Make sure service file existe at /etc/systemd/system/docker.service
  template:
    src: docker.service.j2
    dest: /etc/systemd/system/docker.service
  notify:
    - Reload Docker
  register: docker_servise_status

- name: Reload Daemon if Docker Service Definition changed
  systemd:
    state: started
    daemon_reload: yes
    name: docker
  when: docker_servise_status.changed or docker_socket_status.changed

- name: Make sure /etc/docker existe
  file:
    path: /etc/docker
    state: directory

- name: Configure /etc/docker/daemon.json
  copy:
    dest: /etc/docker/daemon.json
    src: daemon-{{ ansible_distribution }}.json
  notify:
    - Reload Docker

- name: Make sure docker is running
  systemd:
    state: started
    name: docker
    enabled: yes
