---
- name: Install runtime
  include_tasks: "{{ agorakube_base_components.container.engine  }}.yaml"

- name: Uninstall docker
  include_tasks: uninstall-docker.yaml
  when: agorakube_base_components.container.engine == "docker"
  tags: [ 'never', 'uninstall' ]

- name: Clear Containerd Components
  include_tasks: delete-containerd-components.yaml
  when: agorakube_base_components.container.engine == "containerd"
  tags: ['never', 'uninstall']
