---
- name: Create tempdir
  tempfile:
    state: directory
    suffix: argocd
  register: argocd_tempdir
  changed_when: false

- name: Render templates
  template:
    dest: "{{ argocd_tempdir.path }}/argocd.yaml"
    src: "argocd.yaml.j2"
  changed_when: false

- name: Apply templates
  command: kubectl --kubeconfig {{ pki_path }}/kubeconfigs/admin/admin.conf apply -f {{ argocd_tempdir.path }}/argocd.yaml
  register: apply_argocd
  changed_when: >
    apply_argocd.stdout is search("created")
    or apply_argocd.stdout is search("configured")

- name: Cleanup tempdir
  file:
    state: absent
    path: "{{ argocd_tempdir.path }}"
  changed_when: false

#- name: Verify if argocd pods has successfully started
#  command: kubectl --kubeconfig {{ pki_path }}/kubeconfigs/admin/admin.conf get deploy -n argocd-system
#  changed_when: false
#  register: argocd_deployment
#  until: argocd_deployment.stdout.find(agorakube_features.argocd.replicas.controller_manager | string + "/" + agorakube_features.argocd.replicas.controller_manager | string) != -1
#  retries: 300
#  delay: 10
#  run_once: true
