---
- name: Create tempdir Grafana
  tempfile:
    state: directory
    suffix: grafana
  register: grafana_tempdir
  changed_when: false

- name: Render templates Grafana
  template:
    dest: "{{ grafana_tempdir.path }}/grafana.yaml"
    src: "grafana.yaml.j2"
  changed_when: false

- name: Apply templates Grafana
  command: kubectl --kubeconfig {{ pki_path }}/kubeconfigs/admin/admin.conf apply -f {{ grafana_tempdir.path }}/grafana.yaml --force
  register: apply_grafana
  changed_when: >
    apply_grafana.stdout is search("created")
    or apply_grafana.stdout is search("configured")
- name: Cleanup tempdir
  file:
    state: absent
    path: "{{ grafana_tempdir.path }}"
  changed_when: false


- name: Wait for Grafana to be deployed
  command: kubectl --kubeconfig {{ pki_path }}/kubeconfigs/admin/admin.conf get deploy -n supervision grafana
  changed_when: false
  register: grafana_deployment
  until: grafana_deployment.stdout.find("1/1") != -1
  retries: 300
  delay: 10
  run_once: true
