---
- name: Folder creation /etc/kubernetes/pki /etc/kubernetes/pki/etcd
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /etc/kubernetes
    - /etc/kubernetes/pki
    - /etc/kubernetes/pki/etcd
    - /etc/kubernetes/pki/proxy/
    - /etc/kubernetes/pki/token_authentication_keys

- name: Import kubernetes ca.crt
  copy:
    src: "{{ data_path }}/certificates/intermediate/kubernetes-ca/signed/kubernetes-ca.pem"
    dest: /etc/kubernetes/pki/ca.crt
  notify:
    - Restart kube-apiserver service
    - Restart kube-controller-manager service

- name: Import kubernetes ca.key
  copy:
    src: "{{ data_path }}/certificates/intermediate/kubernetes-ca/kubernetes-ca-key.pem"
    dest: /etc/kubernetes/pki/ca.key
  notify:
    - Restart kube-apiserver service
    - Restart kube-controller-manager service

####
- name: Import kubernetes sa.crt
  copy:
    src: "{{ data_path }}/certificates/intermediate/sa/signed/sa.pem"
    dest: /etc/kubernetes/pki/sa.crt
  notify:
    - Restart kube-apiserver service

- name: Import kubernetes sa.key
  copy:
    src: "{{ data_path }}/certificates/intermediate/sa/sa-key.pem"
    dest: /etc/kubernetes/pki/sa.key
  notify:
    - Restart kube-controller-manager service
####
- name: Import kubernetes apiserver.crt
  copy:
    src: "{{ data_path }}/certificates/end/kube-apiserver/{{ ansible_fqdn }}/kube-apiserver.pem"
    dest: /etc/kubernetes/pki/apiserver.crt
  notify:
    - Restart kube-apiserver service

- name: Import kubernetes apiserver.key
  copy:
    src: "{{ data_path }}/certificates/end/kube-apiserver/{{ ansible_fqdn }}/kube-apiserver-key.pem"
    dest: /etc/kubernetes/pki/apiserver.key
  notify:
    - Restart kube-apiserver service

####


- name: Import new token authentication key
  copy:
    src: "{{ item }}"
    dest: /etc/kubernetes/pki/token_authentication_keys/
  with_fileglob:
    - "{{ data_path }}/authentication_keys/*"

- name: Import apiserver-kubelet-client.crt
  copy:
    src: "{{ data_path }}/certificates/end/kube-apiserver-kubelet-client/kube-apiserver-kubelet-client.pem"
    dest: /etc/kubernetes/pki/apiserver-kubelet-client.crt
  notify:
    - Restart kube-apiserver service

- name: Import apiserver-kubelet-client.key
  copy:
    src: "{{ data_path }}/certificates/end/kube-apiserver-kubelet-client/kube-apiserver-kubelet-client-key.pem"
    dest: /etc/kubernetes/pki/apiserver-kubelet-client.key
  notify:
    - Restart kube-apiserver service

- name: Import apiserver-etcd-client.crt
  copy:
    src: "{{ data_path }}/certificates/end/kube-apiserver-etcd-client/kube-apiserver-etcd-client.pem"
    dest: /etc/kubernetes/pki/apiserver-etcd-client.crt
  notify:
    - Restart kube-apiserver service

- name: Import apiserver-etcd-client.key
  copy:
    src: "{{ data_path }}/certificates/end/kube-apiserver-etcd-client/kube-apiserver-etcd-client-key.pem"
    dest: /etc/kubernetes/pki/apiserver-etcd-client.key
  notify:
    - Restart kube-apiserver service

- name: Import certificates etcd/ca.crt
  copy:
    src: "{{ data_path }}/certificates/intermediate/etcd-ca/signed/etcd-ca.pem"
    dest: /etc/kubernetes/pki/etcd/ca.crt
  notify:
    - Restart kube-apiserver service

- name: Import kubernetes-front-proxy-ca.crt
  copy:
    src: "{{ data_path }}/certificates/intermediate/kubernetes-front-proxy-ca/signed/kubernetes-front-proxy-ca.pem"
    dest: "/etc/kubernetes/pki/front-proxy-ca.crt"

- name: Import apiextention client certificate
  copy:
    src: "{{ data_path }}/certificates/end/front-proxy-client/front-proxy-client.pem"
    dest: "/etc/kubernetes/pki/proxy/front-proxy-client.crt"

- name: Import apiextention client certificate
  copy:
    src: "{{ data_path }}/certificates/end/front-proxy-client/front-proxy-client-key.pem"
    dest: "/etc/kubernetes/pki/proxy/front-proxy-client.key"
