name: ansible-lint-agorakube

on:
  pull_request:
    branches: 
      - master

jobs:
  ansible_lint:
    runs-on: ubuntu-latest
    name: A job to lint Ansible Playbooks and roles for Agorakube
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: test ansible lint
      uses: ./actions/ansible-lint
      with:
        lint-config-file: ' '
