name: agorakube-check

on:
  pull_request:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Lint Agorakube Playbooks and roles
      uses: ansible/ansible-lint-action@v4.1.0
      with:
        targets: ""
        args: "-c ansible-lint.conf"
